# Generated by Django 3.2 on 2021-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210505_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tumb',
        ),
        migrations.AddField(
            model_name='image',
            name='is_thumb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
