# Generated by Django 3.2 on 2021-05-05 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('costomer', 'costumer'), ('store', 'store')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='pemilik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costumer.location'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costumer.location'),
        ),
    ]
