# Generated by Django 3.2 on 2021-05-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0002_auto_20210505_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, verbose_name=' Username '),
        ),
    ]
