# Generated by Django 3.2 on 2021-06-02 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0002_tokennotif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pemilik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
    ]
