# Generated by Django 3.2 on 2021-06-07 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0003_alter_store_pemilik'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='banner store'),
        ),
        migrations.AddField(
            model_name='store',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profil', verbose_name='profile store '),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+xxx / 08xxx'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
