# Generated by Django 3.2 on 2021-05-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0004_auto_20210508_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_address', to='costumer.store'),
        ),
    ]
