# Generated by Django 3.2 on 2021-06-11 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0004_auto_20210607_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='location',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='primary'),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='egi', max_length=50, verbose_name='nama lengkap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='name_location',
            field=models.CharField(choices=[('rumah', 'rumah'), ('kantor', 'kantor')], default='kantor', max_length=50, verbose_name='mark_as'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='other',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='patokan alamat '),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+xxx / 08xxx'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='nomor handphone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+xxx / 08xxx'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=300, verbose_name='provinsi ,kota ,kecamatan ,kode poss '),
        ),
    ]
