# Generated by Django 3.2 on 2021-07-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0005_auto_20210611_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='posttal_code',
            field=models.IntegerField(default=43192, verbose_name='postal_code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=300, verbose_name='provinsi ,kota ,kecamatan '),
        ),
    ]
