# Generated by Django 3.2 on 2021-07-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0006_auto_20210721_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='posttal_code',
            new_name='postal_code',
        ),
    ]
