# Generated by Django 3.2 on 2021-07-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0007_rename_posttal_code_location_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
