# Generated by Django 3.2 on 2021-05-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_ht',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
