# Generated by Django 3.2 on 2021-05-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('payment', 'payment'), ('delivery', 'delivery'), ('finish', 'finish'), ('cancel', 'cancel')], default='payment', max_length=50),
        ),
    ]
