# Generated by Django 3.2 on 2021-05-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0002_tokennotif'),
        ('order', '0004_remove_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='costumer.location'),
            preserve_default=False,
        ),
    ]
