# Generated by Django 3.2 on 2021-08-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_paid',
            new_name='ongkir',
        ),
    ]
